# Generated by Django 3.2.12 on 2022-03-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originhubs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queried_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=250, null=True)),
                ('user_email', models.CharField(blank=True, max_length=250, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=250, null=True)),
                ('user_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Queried_list',
                'verbose_name_plural': 'Queried_lists',
            },
        ),
    ]
